version: 2
jobs:
  build:
    docker:
      - image: bioconda/bioconda-utils-build-env


    steps:

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date
          
      - run:
          name: Downloading REPO
          command: curl -LOk https://codeload.github.com/abhijeetpnwr/circleci-101/zip/master 
          
      - run:
          name: Installl unzip
          command: yum -y install unzip

      - run:
          name: unzip code
          command: unzip master && cd circleci-101-master && ls -a
      
      - run:
          name: Download Conda
          command: curl -O https://repo.continuum.io/archive/Anaconda3-5.0.1-Linux-x86_64.sh
                   
      - run:
          name: Download other conda recipes
          command: curl -LOk https://codeload.github.com/faircloth-lab/conda-recipes/zip/master && unzip master && cd conda-recipes-master/ && ls -l
          
       - run:
          name: Install BWA
          command: cd circleci-101-master/recipes/ && pwd && /opt/conda/condabin/conda build BlastPlus
          


