version: 2
jobs:
  build:
    docker:
      - image: pivotaldata/centos7-dev

    steps:

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date
          
      - run:
          name: Downloading REPO
          command: curl -LOk https://codeload.github.com/abhijeetpnwr/circleci-101/zip/master && ls -l && unzip master.zip && ls -l
      
      - run:
          name: Download Conda
          command: curl -O https://repo.continuum.io/archive/Anaconda3-5.0.1-Linux-x86_64.sh
          
      - run:
          name: Install BWA
          command: cd /root/circleci-101/recipes/ && /opt/conda/condabin/conda build BlastPlus


