version: 2		 package:
 jobs:		   name: blast-plus
   build:		
     docker:		
       - image: bioconda/bioconda-utils-build-env		
     steps:
     - run:		 # These are compiled binaries. The true source is 
           name: Greeting		 # ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.2.31/ncbi-blast-2.2.31+-src.tar.gz 
           command: echo Hello, world.
           
